### ISSUE TITLE
Use ICMPv6EchoRequest() instead of ICMPv6()

### ISSUE THREAD

**Issue by davehouser1** [TeddyGuo/tping#7]
Not sure which version of Scapy this is running but scapy==2.4.3 I had to use ICMPv6EchoRequest() instead of ICMPv6().
This error happens if ICMPv6() is used:

```
Traceback (most recent call last):
  File "./tping.py", line 153, in <module>
    tping.run()
  File "./tping.py", line 120, in run
    l4_pkt = l3_pkt/ICMPv6()
NameError: name 'ICMPv6' is not defined
```

**Comment by TeddyGuo** [comment]
I have fixed the issue.

Thank you for the advice.
